In [1]:
# Part 1 - Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('house price.csv')
X = dataset.iloc[:,[-1]].values
y = dataset.iloc[:, [1]].values
dataset

Case  House Price (Y)  House Size (X)
0     1           199000            1100
1     2           245000            1400
2     3           319000            1425
3     4           240000            1550
4     5           312000            1600
5     6           279000            1700
6     7           310000            1700
7     8           308000            1875
8     9           405000            2350
9    10           324000            2450

In [2]:
# Feature Scaling
# from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
sc_X = MinMaxScaler()
X = sc_X.fit_transform(X)
sc_y = MinMaxScaler()
y = sc_y.fit_transform(y)

C:\Users\nakhon\Anaconda3\envs\t81_558_deep_learning\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\nakhon\Anaconda3\envs\t81_558_deep_learning\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [3]:
# Fitting Simple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()    # Create linear regression object
regressor.fit(X, y)   # Train the model using the training sets


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [4]:
regressor.coef_

array([[0.70146172]])

In [5]:
regressor.intercept_ 

array([0.1420957])

In [6]:
from sklearn.metrics import r2_score
y_true = y
y_pred = regressor.predict(X)

print(r2_score(y_true, y_pred) )
print(sc_X.inverse_transform(X))
print()
print(sc_y.inverse_transform(y_pred).round(0))

0.6168385500236037
[[1100.]
 [1400.]
 [1425.]
 [1550.]
 [1600.]
 [1700.]
 [1700.]
 [1875.]
 [2350.]
 [2450.]]

[[228272.]
 [260383.]
 [263059.]
 [276439.]
 [281791.]
 [292494.]
 [292494.]
 [311226.]
 [362069.]
 [372773.]]
